version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/deenyyDB
      - SPRING_DATASOURCE_USERNAME=deenyy
      - SPRING_DATASOURCE_PASSWORD=13081990IrA
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=deenyyDB
      - POSTGRES_USER=deenyy
      - POSTGRES_PASSWORD=13081990IrA
    ports:
      - "5432:5432"
